blank_issues_enabled: false
contact_links:
  - name: General Questions
    url: https://github.com/Schuylerzheng/Miner/discussions
    about: Please ask on https://github.com/Schuylerzheng/Miner/discussions